services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
      target: app_dev
    env_file:
      - .docker.env
    entrypoint: /bin/sh
    ports:
      - ${DOCKER_APP_PORT:-6006}:6006
    working_dir: /srv/app
    volumes:
      - ./:/srv/app
    tty: true
