name: ReleasePreRelease
run-name: ${{ github.actor }} is releasing a new version
on:
  workflow_dispatch:
    branches:
      - release/v[0-9]+.[0-9]+.0
jobs:
  releasePreRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.WOLF_GITBOT_PAT }}
      - name: Set git credentials
        uses: ./.github/workflows/actions/git-config
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('./pnpm-lock.yaml') }}
      - name: Prepare release
        run: ./.github/bin/prepare-release.sh
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.WOLF_GITBOT_PAT }}
      - name: Build new release
        id: build
        run: ./.github/bin/build.sh
        shell: bash
        env:
          SP_WO_MICROSERVICES_CI_SECRET: ${{ secrets.SP_WO_MICROSERVICES_CI_SECRET }}
          SP_WO_MICROSERVICES_CI_ID: ${{ secrets.SP_WO_MICROSERVICES_CI_ID }}
          DOCKER_IMAGE_REGISTRY: ${{ vars.DOCKER_IMAGE_REGISTRY }}
          DOCKER_IMAGE_REPOSITORY_BASE: ${{ vars.DOCKER_IMAGE_REPOSITORY_BASE }}
          BUILD_MODE: 'prod'
          GH_TOKEN: ${{ secrets.WOLF_GITBOT_PAT }}
      - name: Publish new release
        run: ./.github/bin/publish.sh
        shell: bash
        env:
          SERVE_STATIC_IMAGE_NAME: ${{ steps.build.outputs.SERVE_STATIC_IMAGE_NAME }}
